language: node_js
node_js:
  - 'stable'
services:
  - mysql
before_script:
  - cd ./server
  - npm ci
  - mysql -u root --password='' -e 'create database shortly'
after_script:
  - node .travis/submit.js
